main: ${PACKAGE}.Main
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.11"
softdepend: [PlaceholderAPI]
author: volcqnn
description: A Minecraft plugin that adds country tags to players based on their IP address.
permissions:
  countrytags.tag.show:
    description: Allows the player's country tag to be displayed.
    default: true
